"use client";
import { useMemo, useState } from "react";
import SectionHero from "@/components/SectionHero";
import { diplomaAreas, faculties, masters } from "@/data/site";
import { ArrowLeft, ArrowRight, CheckCircle2, GraduationCap, IdCard, Send, ShieldCheck, UserRound, FileText } from "lucide-react";

const initial={firstName:"",middleName:"",lastName:"",gender:"",dob:"",nationality:"Somali",phone:"",whatsapp:"",email:"",city:"Mogadishu",address:"",level:"Bachelor",program:faculties[0].title,school:"",graduationYear:"",certificate:"",emergencyName:"",emergencyPhone:"",message:"",agree:false};

export default function ApplyPage(){
  const [step,setStep]=useState(1);const [done,setDone]=useState(false);const [form,setForm]=useState(initial);
  const programs=useMemo(()=>form.level==="Master"?masters:form.level==="Diploma"?diplomaAreas:faculties.map(f=>f.title),[form.level]);
  const set=(name,value)=>setForm(f=>({...f,[name]:value}));
  const next=()=>setStep(s=>Math.min(4,s+1));const back=()=>setStep(s=>Math.max(1,s-1));
  const submit=e=>{e.preventDefault();if(!form.agree)return;const list=JSON.parse(localStorage.getItem("imamApplications")||"[]");const name=[form.firstName,form.middleName,form.lastName].filter(Boolean).join(" ");list.unshift({...form,name,id:Date.now(),status:"New",createdAt:new Date().toISOString()});localStorage.setItem("imamApplications",JSON.stringify(list));setDone(true);window.scrollTo({top:0,behavior:"smooth"});};
  const Field=({label,name,type="text",required=false,placeholder=""})=><label className="text-sm font-bold text-slate-700">{label}{required&&<span className="text-rose-500"> *</span>}<input required={required} type={type} value={form[name]} onChange={e=>set(name,e.target.value)} placeholder={placeholder} className="form-control"/></label>;
  return <><SectionHero eyebrow="Admissions" title="Apply Online" description="A professional multi-step application experience for prospective IMAM University students." image="/images/admissions-open.jpg"/><section className="bg-imam-50 py-16"><div className="mx-auto max-w-6xl px-4 sm:px-6 lg:px-8">{done?<div className="rounded-4xl bg-white p-10 text-center shadow-soft"><CheckCircle2 size={58} className="mx-auto text-imam-600"/><h2 className="mt-5 text-3xl font-black text-imam-950">Application received</h2><p className="mx-auto mt-3 max-w-xl leading-7 text-slate-600">Your application has been saved in this frontend prototype and is visible in the Admin Panel on this browser. A production backend can later issue an application number, email confirmation and document-upload workflow.</p><button onClick={()=>{setDone(false);setStep(1);setForm(initial)}} className="mt-7 rounded-xl bg-imam-600 px-5 py-3 text-sm font-black text-white">Submit another application</button></div>:<div className="grid gap-6 lg:grid-cols-[.32fr_.68fr]"><aside className="h-fit rounded-4xl bg-imam-950 p-6 text-white shadow-soft lg:sticky lg:top-28"><div className="text-xs font-black uppercase tracking-[.18em] text-imam-300">Online Admission</div><h2 className="mt-3 text-2xl font-black">Application Journey</h2><p className="mt-3 text-sm leading-7 text-slate-300">Complete each stage carefully. Your information can be reviewed before final submission.</p><div className="mt-7 space-y-3">{[{n:1,t:"Personal Details",i:UserRound},{n:2,t:"Study Selection",i:GraduationCap},{n:3,t:"Academic & Contact",i:FileText},{n:4,t:"Review & Submit",i:ShieldCheck}].map(x=><div key={x.n} className={`flex items-center gap-3 rounded-2xl p-3 ${step===x.n?"bg-imam-600":"bg-white/5"}`}><span className="grid h-9 w-9 place-items-center rounded-xl bg-white/10"><x.i size={17}/></span><div><div className="text-[10px] font-black uppercase tracking-[.14em] text-imam-200">Step {x.n}</div><div className="text-sm font-black">{x.t}</div></div></div>)}</div><div className="mt-6 rounded-2xl border border-white/10 bg-white/5 p-4 text-xs leading-6 text-slate-300"><IdCard size={17} className="mb-2 text-imam-300"/>Keep your academic certificates and identification documents ready for the final production document-upload workflow.</div></aside><form onSubmit={submit} className="rounded-4xl bg-white p-6 shadow-soft sm:p-9"><div className="mb-7 flex items-center justify-between"><div><div className="text-xs font-black uppercase tracking-[.16em] text-imam-600">Step {step} of 4</div><h2 className="mt-2 text-3xl font-black text-imam-950">{["Personal Information","Choose Your Study","Academic & Contact Details","Review Your Application"][step-1]}</h2></div><div className="hidden text-sm font-black text-imam-600 sm:block">{step*25}%</div></div><div className="mb-8 h-2 overflow-hidden rounded-full bg-slate-100"><div className="h-full rounded-full bg-imam-600 transition-all duration-300" style={{width:`${step*25}%`}}/></div>
  {step===1&&<div className="grid gap-5 sm:grid-cols-2"><Field label="First Name" name="firstName" required/><Field label="Middle Name" name="middleName"/><Field label="Last Name" name="lastName" required/><label className="text-sm font-bold text-slate-700">Gender <span className="text-rose-500">*</span><select required value={form.gender} onChange={e=>set("gender",e.target.value)} className="form-control"><option value="">Select gender</option><option>Male</option><option>Female</option></select></label><Field label="Date of Birth" name="dob" type="date"/><Field label="Nationality" name="nationality"/><Field label="Phone Number" name="phone" required placeholder="+252..."/><Field label="WhatsApp Number" name="whatsapp" placeholder="+252..."/><Field label="Email Address" name="email" type="email"/><Field label="City" name="city"/><label className="sm:col-span-2 text-sm font-bold text-slate-700">Current Address<textarea value={form.address} onChange={e=>set("address",e.target.value)} rows="3" className="form-control" placeholder="District, city, country"/></label></div>}
  {step===2&&<div><div className="grid gap-5 sm:grid-cols-2"><label className="text-sm font-bold text-slate-700">Study Level <span className="text-rose-500">*</span><select value={form.level} onChange={e=>{const level=e.target.value;const p=level==="Master"?masters[0]:level==="Diploma"?diplomaAreas[0]:faculties[0].title;setForm(f=>({...f,level,program:p}))}} className="form-control"><option>Bachelor</option><option>Master</option><option>Diploma</option></select></label><label className="text-sm font-bold text-slate-700">Program / Faculty <span className="text-rose-500">*</span><select value={form.program} onChange={e=>set("program",e.target.value)} className="form-control">{programs.map(p=><option key={p}>{p}</option>)}</select></label></div><div className="mt-6 rounded-3xl bg-imam-50 p-6"><GraduationCap className="text-imam-600"/><h3 className="mt-3 text-xl font-black text-imam-950">Your selected pathway</h3><div className="mt-3 text-sm font-bold text-imam-700">{form.level} • {form.program}</div><p className="mt-3 text-sm leading-7 text-slate-600">The Admissions Office can confirm official duration, entry requirements, intake availability and tuition after reviewing your application.</p></div></div>}
  {step===3&&<div className="grid gap-5 sm:grid-cols-2"><Field label="Previous School / University" name="school" required/><Field label="Graduation Year" name="graduationYear" placeholder="e.g. 2026"/><Field label="Highest Certificate / Qualification" name="certificate" required/><Field label="Emergency Contact Name" name="emergencyName"/><Field label="Emergency Contact Phone" name="emergencyPhone"/><div/><label className="sm:col-span-2 text-sm font-bold text-slate-700">Additional Notes<textarea value={form.message} onChange={e=>set("message",e.target.value)} rows="5" className="form-control" placeholder="Tell Admissions anything important about your application"/></label></div>}
  {step===4&&<div className="space-y-5"><div className="grid gap-4 sm:grid-cols-2">{[{t:"Applicant",v:[form.firstName,form.middleName,form.lastName].filter(Boolean).join(" ")},{t:"Contact",v:form.phone||form.email},{t:"Study Level",v:form.level},{t:"Program",v:form.program},{t:"Previous Institution",v:form.school},{t:"Qualification",v:form.certificate}].map(x=><div key={x.t} className="rounded-2xl bg-imam-50 p-5"><div className="text-xs font-black uppercase tracking-[.14em] text-slate-400">{x.t}</div><div className="mt-2 font-black leading-6 text-imam-950">{x.v||"Not provided"}</div></div>)}</div><label className="flex gap-3 rounded-2xl border border-imam-100 p-5 text-sm leading-7 text-slate-600"><input type="checkbox" checked={form.agree} onChange={e=>set("agree",e.target.checked)} className="mt-1 h-4 w-4 accent-[#2d7eb4]"/><span>I confirm that the information provided is accurate to the best of my knowledge and understand that official documents may be required during the admission review.</span></label></div>}
  <div className="mt-8 flex items-center justify-between border-t border-slate-100 pt-6">{step>1?<button type="button" onClick={back} className="inline-flex items-center gap-2 rounded-xl border border-slate-200 px-5 py-3 text-sm font-black text-slate-700"><ArrowLeft size={16}/> Back</button>:<span/>}{step<4?<button type="button" onClick={next} className="inline-flex items-center gap-2 rounded-xl bg-imam-600 px-6 py-3 text-sm font-black text-white">Continue <ArrowRight size={16}/></button>:<button disabled={!form.agree} className="inline-flex items-center gap-2 rounded-xl bg-imam-600 px-6 py-3 text-sm font-black text-white disabled:cursor-not-allowed disabled:opacity-45"><Send size={16}/> Submit Application</button>}</div></form></div>}</div></section></>}
