import Link from "next/link";
import SectionHero from "@/components/SectionHero";
import MotionReveal from "@/components/MotionReveal";
import VideoShowcase from "@/components/VideoShowcase";
import AnimatedCounter from "@/components/AnimatedCounter";
import SafeImage from "@/components/SafeImage";
import { objectives, onlineImages, stats, university, values } from "@/data/site";
import { ArrowRight, CheckCircle2, Eye, Flag, Gem, Target, Users, BookOpenCheck, Globe2 } from "lucide-react";

export const metadata = { title: "About Us" };

export default function AboutPage(){
  return <>
    <SectionHero eyebrow="About" title="About IMAM University" description="A values-driven university serving students and society through education, research, professional development and community engagement." image="/images/campus-activity-2.jpg"/>

    <section className="bg-white py-20"><div className="mx-auto grid max-w-7xl gap-12 px-4 sm:px-6 lg:grid-cols-[1.05fr_.95fr] lg:px-8">
      <MotionReveal><span className="text-xs font-black uppercase tracking-[.2em] text-imam-600">Background</span><h2 className="mt-4 text-4xl font-black tracking-[-.04em] text-imam-950">Welcome to IMAM University</h2><p className="mt-5 leading-8 text-slate-600">{university.description}</p><p className="mt-4 leading-8 text-slate-600">The university exists to help learners build knowledge, professional capability, ethical responsibility and confidence. Its academic identity combines Islamic values with a forward-looking commitment to education, scientific inquiry and service to society.</p><p className="mt-4 leading-8 text-slate-600">This redesigned website presents IMAM University as a connected academic institution: prospective students can discover programs and admissions, current students can access services, researchers can explore scholarly activity, and the wider public can follow university news and engagement.</p><div className="mt-8 flex flex-wrap gap-3"><Link href="/about/welcome" className="rounded-xl bg-imam-950 px-5 py-3 text-sm font-black text-white">Rector&apos;s Welcome</Link><Link href="/academics" className="rounded-xl border border-imam-200 px-5 py-3 text-sm font-black text-imam-700">Explore Academics</Link></div></MotionReveal>
      <MotionReveal delay={.06} className="grid grid-cols-2 gap-4"><img src="/images/campus-activity-2.jpg" alt="IMAM University campus life" className="h-72 w-full rounded-4xl object-cover shadow-card"/><SafeImage src={onlineImages.students} fallback="/images/presentation-1.jpg" alt="University students in a learning environment" className="mt-10 h-72 w-full rounded-4xl object-cover shadow-card"/><div className="col-span-2 rounded-3xl bg-imam-50 p-6"><div className="grid grid-cols-2 gap-4 sm:grid-cols-4">{stats.map(s=><div key={s.label}><div className="text-2xl font-black text-imam-700"><AnimatedCounter value={s.value} suffix={s.suffix}/></div><div className="mt-1 text-xs font-bold leading-5 text-slate-500">{s.label}</div></div>)}</div></div></MotionReveal>
    </div></section>

    <section className="bg-imam-50 py-20"><div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8"><MotionReveal className="max-w-3xl"><span className="text-xs font-black uppercase tracking-[.2em] text-imam-600">Who we are</span><h2 className="mt-4 text-4xl font-black tracking-[-.04em] text-imam-950">Mission, vision and institutional purpose</h2></MotionReveal><div className="mt-10 grid gap-6 lg:grid-cols-3">{[{icon:Eye,title:"Our Vision",text:university.vision},{icon:Flag,title:"Our Mission",text:university.mission},{icon:Target,title:"Our Purpose",text:"To widen opportunity for higher education, strengthen professional competence, support research and empower youth to contribute positively to society."}].map(x=><MotionReveal key={x.title} className="rounded-3xl border border-imam-100 bg-white p-7 shadow-card"><span className="grid h-12 w-12 place-items-center rounded-2xl bg-imam-100 text-imam-700"><x.icon/></span><h3 className="mt-5 text-xl font-black text-imam-950">{x.title}</h3><p className="mt-3 text-sm leading-7 text-slate-600">{x.text}</p></MotionReveal>)}</div></div></section>

    <section className="bg-white py-20"><div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8"><MotionReveal className="grid gap-10 lg:grid-cols-[.82fr_1.18fr] lg:items-start"><div><span className="text-xs font-black uppercase tracking-[.2em] text-imam-600">University Story</span><h2 className="mt-4 text-4xl font-black tracking-[-.04em] text-imam-950">See the university in motion.</h2><p className="mt-5 leading-8 text-slate-600">Watch the university overview video in a full professional player with play, pause, restart and sound controls. This section can later be replaced with the final institutional film approved by the university.</p><div className="mt-6 space-y-3">{["Professional and responsive video presentation","Accessible player controls","Strong visual preview and university branding","Ready for the final official promotional film"].map(x=><div key={x} className="flex gap-3 text-sm font-bold text-slate-700"><CheckCircle2 size={18} className="mt-0.5 text-imam-600"/>{x}</div>)}</div></div><VideoShowcase/></MotionReveal></div></section>

    <section className="bg-imam-950 py-20 text-white"><div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8"><MotionReveal className="text-center"><span className="text-xs font-black uppercase tracking-[.2em] text-imam-300">Core Values</span><h2 className="mt-4 text-4xl font-black tracking-[-.04em]">The principles behind our academic community</h2></MotionReveal><div className="mt-10 grid gap-5 md:grid-cols-2 lg:grid-cols-3">{values.map(v=><MotionReveal key={v.title} className="rounded-3xl border border-white/10 bg-white/5 p-6"><Gem className="text-imam-300"/><h3 className="mt-4 text-xl font-black">{v.title}</h3><p className="mt-2 text-sm leading-7 text-slate-300">{v.text}</p></MotionReveal>)}</div></div></section>

    <section className="bg-white py-20"><div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8"><MotionReveal className="grid gap-10 lg:grid-cols-2"><div><span className="text-xs font-black uppercase tracking-[.2em] text-imam-600">Objectives</span><h2 className="mt-4 text-4xl font-black tracking-[-.04em] text-imam-950">Education that translates into contribution.</h2><div className="mt-6 space-y-4">{objectives.map(x=><div key={x} className="flex gap-3 rounded-2xl border border-imam-100 p-5"><CheckCircle2 className="mt-1 shrink-0 text-imam-600"/><span className="leading-7 text-slate-600">{x}</span></div>)}</div></div><div className="grid gap-5 sm:grid-cols-2">{[{i:Users,t:"Student Centered",d:"Learning support, academic guidance and student development at the center of the experience."},{i:BookOpenCheck,t:"Quality Education",d:"Clear academic pathways, strong learning habits and continuous improvement in teaching and learning."},{i:Globe2,t:"Global Outlook",d:"A modern university perspective that connects local priorities with wider knowledge and opportunity."},{i:Target,t:"Community Impact",d:"Education, research and service designed to contribute to stronger communities and sustainable development."}].map(x=><div key={x.t} className="rounded-3xl bg-imam-50 p-6"><x.i className="text-imam-600"/><h3 className="mt-4 font-black text-imam-950">{x.t}</h3><p className="mt-2 text-sm leading-7 text-slate-600">{x.d}</p></div>)}</div></MotionReveal></div></section>

    <section className="bg-imam-50 py-16"><div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8"><MotionReveal className="rounded-4xl bg-white p-8 shadow-soft lg:flex lg:items-center lg:justify-between"><div><h2 className="text-3xl font-black text-imam-950">Explore the university in more depth</h2><p className="mt-3 max-w-2xl leading-7 text-slate-600">Read the Rector&apos;s welcome, strategic goals, governance structure, accreditation area and partnership framework.</p></div><Link href="/about/strategic-goals" className="mt-6 inline-flex items-center gap-2 rounded-xl bg-imam-600 px-5 py-3 text-sm font-black text-white lg:mt-0">Continue Exploring <ArrowRight size={17}/></Link></MotionReveal></div></section>
  </>
}
